---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "cm-pulsar-broker"
  labels:
    app: pulsar
data:
{{ toYaml .Values.broker.configData | indent 2 }}
  zookeeperServers: {{ .Values.broker.configData.zookeeperServers }}

---
# deploy zookeeper only when `components.zookeeper` is true
apiVersion: v1
kind: ConfigMap
metadata:
  name: "cm-pulsar-zookeeper"
  labels:
    app: pulsar
data:
{{ toYaml .Values.zookeeper.configData | indent 2 }}
  PULSAR_PREFIX_serverCnxnFactory: org.apache.zookeeper.server.NettyServerCnxnFactory
