---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "cm-pulsar-broker"
  labels:
    app: pulsar
data:
  zookeeperServers: "cm-pulsar-zookeeper:2181"
{{ toYaml .Values.broker.configData | indent 2 }}

---
# deploy zookeeper only when `components.zookeeper` is true
apiVersion: v1
kind: ConfigMap
metadata:
  name: "cm-pulsar-zookeeper"
  labels:
    app: pulsar
data:
  PULSAR_PREFIX_serverCnxnFactory: org.apache.zookeeper.server.NettyServerCnxnFactory
{{ toYaml .Values.zookeeper.configData | indent 2 }}
